# Keys are case insensitive
# Actually when reading the configuration
# all the keys are converted to lowercase
# BUT values are case SENSITIVE, so be carefull
# Configuration has following sections:
# 'common', 'sources', 'destinations'
#
# COMMON section:
#
common:
  allowmac:
  showraw: false
  advertise: 0
  url: http://0.0.0.0/
  txpower: 0
  device: 0
  # writeconfig: ble_gateway/ble_gateway.config.defaults.yaml
  no_messages_timeout: 10
  decode:
  - all
  - unknown
  # mode: SCAN
  mode: GATEWAY
  simulator: false
#
# SOURCES section:
#
# Settings defined in source DEFAULTS are applied first
# to all other defined sources. Additional settings
# defined for a particular source will override settings
# inherited from DEFAULTS
sources:
  # Optional source settings for "*" will be applied to packets
  # which are not matched to any defined mac address
  '*':
    # There is built-in destination called DROP which just discards
    # the packet and can be used in any source definition
    destinations:
    - DROP
    interval: 0
    fields_order:
    decoders:
    - all
    - unknown
  defaults:
    destinations:
    - default_file
    interval: 5
    # fields in fields_order will be first, other fields remain as is
    fields_order:
    - timestamp
    - mac
    decoders:
    - all
  # Mac addresses (as they are keys) will be converted to lowercase
  da:b6:f7:69:c3:45:
    decoders:
    - ruuviraw
    fields_add:
    - location=Ulkona
  e6:16:76:cf:e6:e3:
    decoders:
    - ruuviraw
    fields_add:
    - location=Olohuone
  e2:e2:4f:4d:6c:77:
    decoders:
    - ruuviraw
    fields_add:
    - location=Makuuhuone
#
# DESTINATIONS section:
#
# Settings defined in destination DEFAULTS are applied first
# to all defined destinations. Additional settings
# defined for a particular destination will override settings
# inherited from DEFAULTS
destinations:
  default_file:
    fields_remove:
    - tx_power
    interval: 20
    type: file
    filename: default_file.LOG
    batch: 10
  influxdb_test:
    host: localhost
    port: 8086
    database: ble_test
    username: root
    password: root
    measurement: test
    tags:
    - location
    - mac
    - decoder
  defaults:
    fields_rename:
    - peer=mac
    interval: 6
