#
common:
  device: 1
  scan: true
  showraw: false
  advertise: null
  allowmac: null
  configfile: '-'
  decode: all
  txpower: null
  url: null
  writeconfig: ./ble_gateway/ble_gateway.config.defaults.yaml
#
destinations:
  default_file:
    filename: default_file.log
    type: file
#
sources:
  defaults:
    decoders:
    - all
    destinations:
    - default_file
    intervall: 20
