#
common:
  device: 0
  scan: false
  showraw: false
  advertise: null
  allowmac: null
  decode: all
  txpower: 0
  url: null
  writeconfig: null
#
destinations:
  default_file:
    filename: default_file.LOG
    type: file
  test_influxdb:
    host: localhost
    port: 8086
#
sources:
  E2:E2:4F:4D:6C:77:
    decoders:
    - ruuviraw
    fields_add:
    - location=Makuuhuone
  defaults:
    decoders:
    - all
    destinations:
    - default_file
    interval: 20
# Bogus sections
something:
  invalid: whatnot
