# Keys are case insensitive
# Actually when reading the configuration
# all the keys are converted to lowercase
# BUT values are case SENSITIVE, so be carefull
# Configuration has following sections:
# 'common', 'sources', 'destinations'
#
# COMMON section:
#
common:
  allowmac:
  - da:b6:f7:69:c3:45
  - e6:16:76:cf:e6:e3
  - e2:e2:4f:4d:6c:77
  - dc:ad:98:6e:75:a4
  - e8:8d:16:b2:bb:73
  - d2:c5:d2:a4:d6:56
  showraw: false
  advertise: 0
  url: http://0.0.0.0/
  txpower: 0
  device: 0
  # writeconfig: ble_gateway/ble_gateway.config.defaults.yaml
  no_messages_timeout: 10
  decode:
  - all
  - unknown
  # mode: SCAN
  mode: GATEWAY
  simulator: 0
#
# SOURCES section:
#
# Settings defined in source DEFAULTS are applied first
# to all other defined sources. Additional settings
# defined for a particular source will override settings
# inherited from DEFAULTS
sources:
  # Optional source settings for "*" will be applied to packets
  # which are not matched to any defined mac address
  '*':
    # There is built-in destination called DROP which just discards
    # the packet and can be used in any source definition
    destinations:
    - DROP
    interval: 0
    decoders:
    - all
    - unknown
  defaults:
    destinations:
    - default_file
    interval: 20
    # fields in fields_order will be first, other fields remain as is
    fields_order:
    - timestamp
    - mac
    decoders:
    - all
  # Mac addresses (as they are keys) will be converted to lowercase
  da:b6:f7:69:c3:45:
    decoders:
    - ruuviraw
    destinations:
    - influxdb1
    fields_add:
    - location=Ulkona
  e6:16:76:cf:e6:e3:
    decoders:
    - ruuviraw
    destinations:
    - influxdb1
    fields_add:
    - location=Olohuone
  e2:e2:4f:4d:6c:77:
    decoders:
    - ruuviraw
    destinations:
    - influxdb1
    fields_add:
    - location=Makuuhuone
  dc:ad:98:6e:75:a4:
    decoders:
    - ruuviraw
    destinations:
    - influxdb1
    fields_add:
    - location=Alapohja
  e8:8d:16:b2:bb:73:
    decoders:
    - ruuviraw
    destinations:
    - influxdb_test
    fields_add:
    - location=Emmanhuone
  d2:c5:d2:a4:d6:56:
    decoders:
    - ruuviraw
    destinations:
    - influxdb1
    fields_add:
    - location=Joelinhuone
#
# DESTINATIONS section:
#
# Settings defined in destination DEFAULTS are applied first
# to all defined destinations. Additional settings
# defined for a particular destination will override settings
# inherited from DEFAULTS
destinations:
  default_file:
    fields_remove:
    - tx_power
    interval: 20
    type: file
    filename: default_file.LOG
    batch: 10
  influxdb1:
    type: influxdb
    host: jani-3620
    port: 8086
    database: ruuvi
    username: root
    password: root
    measurement: ruuvi_measurements
    batch: 10
    interval: 30
    tags:
    - location
    - mac
    - decoder
    fields_rename:
    - acceleration_x=accelerationX
    - acceleration_y=accelerationY
    - acceleration_z=accelerationZ
    - movement_counter=movementCounter
    - measurement_sequence_number=measurementSequenceNumber
    - battery=batteryVoltage
    - tx_power=txPower
    values_uppercase:
    - mac
  thingspeak1:
    type: thingspeak
    url:
    write_api_key: ruuvi_measurements
    batch: 10
    interval: 30
    mappings:
    # - mac+fieldname=channelid+fieldid
    - da:b6:f7:69:c3:45+temperature=123456+1
    - da:b6:f7:69:c3:45+humidity=123456+2
    - e6:16:76:cf:e6:e3
    - e2:e2:4f:4d:6c:77
    - dc:ad:98:6e:75:a4
    - e8:8d:16:b2:bb:73
    - d2:c5:d2:a4:d6:56
defaults:
    fields_rename:
    - peer=mac
    interval: 0
