advertise: null
allowmac: null
configfile: '-'
decode: null
destinations:
  default_file:
    filename: default_file.out
    type: file
device: null
scan: false
showraw: false
sources:
  default:
    decoders:
    - all
    - unknown
    destinations:
    - default_file
    intervall: 10
txpower: null
url: null
writeconfig: ./ble_gateway/ble_gateway.config.defaults.yaml
