#
device: 1
scan: true
showraw: false
advertise: null
allowmac: null
configfile: '-'
decode: all
txpower: null
url: null
writeconfig: ./ble_gateway/ble_gateway.config.defaults.yaml
#
destinations:
  default_file:
    filename: default_file.out
    type: file
#
sources:
  default:
    decoders:
    - all
    - unknown
    destinations:
    - default_file
    intervall: 10
